<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472;net8.0-windows</TargetFramework>
    <RootNamespace>pdfdir</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    
    <!-- 为不同框架设置条件编译符号 -->
    <DefineConstants Condition="'$(TargetFramework)' == 'net472'">NETFRAMEWORK;NET472</DefineConstants>
    <DefineConstants Condition="'$(TargetFramework)' == 'net8.0-windows'">NET8_0;WINDOWS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="itext" Version="9.5.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.5.0" />
  </ItemGroup>
  </ItemGroup>

</Project>
