name: WPF Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        cache: true
    
    - name: Build
      run: |
        dotnet publish -c Release -o ./publish-single -p:DebugType=none -p:DebugSymbols=false -p:PublishSingleFile=true -p:SelfContained=false
        dotnet publish -c Release -o ./publish-multi -p:DebugType=none -p:DebugSymbols=false -p:PublishSingleFile=true -p:SelfContained=false
    
    - name: Upload artifact single
      uses: actions/upload-artifact@v4
      with:
        name: pdfdir-single
        path: ./publish-single/
        retention-days: 30
    - name: Upload artifact multi
      uses: actions/upload-artifact@v4
      with:
        name: pdfdir-multi
        path: ./publish-multi/
        retention-days: 30