name: Release

permissions: write-all

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build
      run: |
        dotnet publish .\PdfdirWin\PdfdirWin.csproj -c Release -o ./WinPdfdir -p:DebugType=none -p:DebugSymbols=false -p:PublishSingleFile=true -p:SelfContained=false
    - name: zip
      run: |
        Compress-Archive -Path ./WinPdfdir/* -DestinationPath ./WinPdfdir.zip -Force
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          Release ${{ env.VERSION }}
        files: |
          ./WinPdfdir.zip

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}