name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: setup test
      run: |
        Invoke-WebRequest -Uri "https://github.com/xiaochuan-dev/pdf-static/releases/download/0.0.4/file.pdf" -OutFile "$tempPath\file.pdf"
        Invoke-WebRequest -Uri "https://github.com/xiaochuan-dev/pdf-static/releases/download/0.0.4/data.txt" -OutFile "$tempPath\data.txt"
        echo "MY_TEST_FILEPATH=$tempPath\file.pdf" >> $env:GITHUB_ENV
        echo "MY_TEST_DATAPATH=$tempPath\data.txt" >> $env:GITHUB_ENV
    - name: test

      run: |
        dotnet test 

    - name: Upload artifact single
      uses: actions/upload-artifact@v5
      with:
        name: TestLogs
        path: ./PdfdirWin.Test/TestLogs/
        retention-days: 30