name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: test
      run: |
        dotnet test 

    - name: Upload artifact single
      uses: actions/upload-artifact@v5
      with:
        name: TestLogs
        path: ./PdfdirWin.Test/TestLogs/
        retention-days: 30